name: Podman

on:
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install QEMU for multi-architecture builds
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static

      - name: Log in to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_LOWERCASE }}
          tags: latest
          platforms: linux/amd64,linux/arm64
          containerfiles: |
            ./Containerfile
          extra-args: |
            --layers=true
            --cache-from=ghcr.io/${{ env.REPO_LOWERCASE }}-cache
            --cache-to=ghcr.io/${{ env.REPO_LOWERCASE }}-cache

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io
